export type Language = "de" | "en";

const translations = {
  en: {
    dashboard: { overview: "Overview", dashboard: "Dashboard", revenue: "Revenue", expenses: "Expenses", netProfit: "Net Profit", monthlyPerformance: "Monthly Performance", openOrders: "Open Orders", paidOrders: "Paid Orders", markets: "Markets", allYears: "All", reportTitle: "Financial Report", summary: "Summary", totalRevenue: "Total Revenue:", totalExpenses: "Total Expenses:", monthlyBreakdown: "Monthly Breakdown", month: "Month", generatingReport: "Generating Report...", reportError: "Could not generate report.", shareReport: "Share Report" },
    orders: { title: "Orders", noOrders: "No orders yet", noOrdersSub: "Create your first order to start tracking sales", newOrder: "New Order", editOrder: "Edit Order", invoice: "Invoice", customer: "Customer", customerName: "Customer name", email: "Email (optional)", street: "Street + No.", zip: "ZIP", city: "City", country: "Country", streetPlaceholder: "123 Main St", zipPlaceholder: "12345", cityPlaceholder: "City", invoiceDateLabel: "Invoice Date", serviceDateLabel: "Service Date", shippingCostLabel: "Shipping", posLabel: "Pos.", items: "Items", itemName: "Item name", qty: "Qty", price: "Price", notes: "Notes", additionalNotes: "Additional notes (optional)", total: "Total", createOrder: "Create Order", orderDetails: "Order Details", updateStatus: "Update Status", deleteOrder: "Delete Order", deleteConfirm: "Are you sure you want to delete this order?", deleteCancel: "Cancel", deleteAction: "Delete", changeStatus: "Change Status", changeStatusConfirm: "Set order to", confirm: "Confirm", missingInfo: "Missing Info", enterCustomerName: "Please enter a customer name.", fillItemNames: "Please fill in all item names.", item: "item", items_plural: "items", cannotUndo: "This cannot be undone.", createInvoice: "Create Invoice", invoiceTitle: "INVOICE", invoiceFrom: "From", invoiceTo: "To", invoiceDate: "Date", invoiceNumber: "Invoice No.", invoiceItem: "Item", invoiceQty: "Qty", invoiceUnitPrice: "Unit Price", invoiceAmount: "Amount", invoiceSubtotal: "Subtotal", invoiceTotal: "Total", invoiceNotes: "Notes", invoiceGenerated: "Invoice generated successfully.", invoiceError: "Could not generate invoice.", shareInvoice: "Share Invoice", invoiceThankYou: "Thank you for your purchase!", orderDate: "Date", orderDatePlaceholder: "Order date", processingStatus: "Processing Status", processingStatusTodo: "To Do", processingStatusInProgress: "In Progress", processingStatusDone: "Done", comment: "Comment", commentPlaceholder: "Internal comment..." },
    markets: { title: "Markets", noMarkets: "No markets yet", noMarketsSub: "Add your first market event to track sales", newMarket: "New Market", eventDetails: "Event Details", marketName: "Market name", location: "Location (optional)", costs: "Costs", standFee: "Stand Fee", travelCost: "Travel Cost", notes: "Notes", additionalNotes: "Additional notes (optional)", createMarket: "Create Market", marketDetails: "Market Details", sales: "Sales", profit: "Profit", costBreakdown: "Cost Breakdown", travel: "Travel", noSales: "No sales recorded yet. Use the + button to add quick sales.", itemDescription: "Item description", deleteSale: "Delete Sale", removeSale: "Remove this sale?", deleteMarket: "Delete Market", deleteMarketConfirm: "This will also remove all associated sales.", deleteCancel: "Cancel", deleteAction: "Delete" },
    expenses: { title: "Expenses", noExpenses: "No expenses yet", noExpensesSub: "Track your business expenses to see accurate profit", newExpense: "New Expense", description: "Description", whatSpent: "What did you spend on?", amount: "Amount", category: "Category", addExpense: "Add Expense", expenseDate: "Date", expenseDatePlaceholder: "Expense date", deleteExpense: "Delete Expense", areYouSure: "Are you sure?", cancel: "Cancel", delete: "Delete", total: "Total", categories: { Materials: "Materials", Shipping: "Shipping", Subscriptions: "Subscriptions", Tools: "Tools", Marketing: "Marketing", Packaging: "Packaging", Other: "Other" } },
    settings: { title: "Settings", companyProfile: "Company Profile", companyName: "Company Name", address: "Address", email: "Email", phone: "Phone", taxNote: "Tax Note (shown on invoices)", taxNotePlaceholder: "e.g. As per \u00A7 19 UStG, no VAT is charged.", smallBusinessNote: "Small business note", defaultShippingCost: "Default shipping cost", notSet: "Not set", dataBackup: "Data & Backup", exportBackup: "Export Backup", restoreBackup: "Restore from Backup", factoryReset: "Factory Reset", privacy: "Privacy", privacyText: "Vendora stores your data securely in the cloud, protected by your account. No tracking or analytics. You own 100% of your data.", exportComplete: "Export Complete", exportSuccess: "Your data has been exported successfully.", exportFailed: "Export Failed", exportError: "Could not export data. Please try again.", importComplete: "Import Complete", importSuccess: "Your data has been restored successfully.", importFailed: "Import Failed", importError: "Could not read the backup file. Please try again.", resetTitle: "Factory Reset", resetMessage: "This will permanently delete all your data. This action cannot be undone.", resetCancel: "Cancel", resetAction: "Delete Everything", resetComplete: "Reset Complete", resetSuccess: "All data has been wiped.", language: "Language", appearance: "Appearance", dark: "Dark", light: "Light", system: "System" },
    tabs: { dashboard: "Dashboard", orders: "Orders", markets: "Markets", expenses: "Expenses", settings: "Settings" },
    common: { loading: "Loading...", cancel: "Cancel", delete: "Delete", confirm: "Confirm", save: "Save" },
    auth: { login: "Login", register: "Register", email: "Email", password: "Password", confirmPassword: "Confirm Password", loginSubtitle: "Sign in to your account", registerSubtitle: "Create your account", noAccount: "Don't have an account?", hasAccount: "Already have an account?", loginError: "Invalid email or password", registerError: "Could not create account. Email may already be in use.", passwordMismatch: "Passwords do not match", passwordTooShort: "Password must be at least 8 characters", logout: "Logout", account: "Account", forgotPassword: "Forgot password?", resetTitle: "Reset Password", resetEmailSubtitle: "Enter your email address and we'll send you a reset link.", sendResetLink: "Send Reset Link", resetSuccess: "Password Reset", resetSuccessMessage: "Check your email for a password reset link.", resetError: "Could not send reset link. Please try again." },
    subscription: { trialDaysLeft: "{days} days left in your free trial", expired: "Free trial ended", expiredSub: "Subscribe to create new orders, markets & expenses.", upgrade: "Subscribe", upgradeTitle: "Subscribe to Vendora", upgradeDescription: "Get unlimited access to all features for just 2,99\u20AC/month.", upgradeButton: "Subscribe for 2,99\u20AC/month", features: "Create orders & invoices, track markets, manage expenses", currentPlan: "Current Plan", trial: "Free Trial", active: "Active Subscription", cancelled: "Cancelled", readOnly: "This feature requires an active subscription." },
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
  },
  de: {
    dashboard: { overview: "\u00DCbersicht", dashboard: "Dashboard", revenue: "Umsatz", expenses: "Ausgaben", netProfit: "Nettogewinn", monthlyPerformance: "Monatliche Entwicklung", openOrders: "Offene Auftr\u00E4ge", paidOrders: "Bezahlte Auftr\u00E4ge", markets: "M\u00E4rkte", allYears: "Alle", reportTitle: "Finanzbericht", summary: "Zusammenfassung", totalRevenue: "Gesamtumsatz:", totalExpenses: "Gesamtausgaben:", monthlyBreakdown: "Monatliche Aufschl\u00FCsselung", month: "Monat", generatingReport: "Bericht wird erstellt...", reportError: "Bericht konnte nicht erstellt werden.", shareReport: "Bericht teilen" },
    orders: { title: "Aufträge", noOrders: "Noch keine Aufträge", noOrdersSub: "Erstelle deinen ersten Auftrag, um Verkäufe zu verfolgen", newOrder: "Neuer Auftrag", editOrder: "Auftrag bearbeiten", invoice: "Rechnung", customer: "Kunde", customerName: "Kundenname", email: "E-Mail (optional)", street: "Straße + Hausnr.", zip: "PLZ", city: "Ort", country: "Land", streetPlaceholder: "Musterstraße 1", zipPlaceholder: "12345", cityPlaceholder: "Musterstadt", invoiceDateLabel: "Rechnungsdatum", serviceDateLabel: "Leistungsdatum", shippingCostLabel: "Versandkosten", posLabel: "Pos.", items: "Artikel", itemName: "Artikelname", qty: "Anz.", price: "Preis", notes: "Notizen", additionalNotes: "Zus\u00E4tzliche Notizen (optional)", total: "Gesamt", createOrder: "Auftrag erstellen", orderDetails: "Auftragsdetails", updateStatus: "Status \u00E4ndern", deleteOrder: "Auftrag l\u00F6schen", deleteConfirm: "M\u00F6chtest du diesen Auftrag wirklich l\u00F6schen?", deleteCancel: "Abbrechen", deleteAction: "L\u00F6schen", changeStatus: "Status \u00E4ndern", changeStatusConfirm: "Status setzen auf", confirm: "Best\u00E4tigen", missingInfo: "Fehlende Angaben", enterCustomerName: "Bitte gib einen Kundennamen ein.", fillItemNames: "Bitte f\u00FClle alle Artikelnamen aus.", item: "Artikel", items_plural: "Artikel", cannotUndo: "Dies kann nicht r\u00FCckg\u00E4ngig gemacht werden.", createInvoice: "Rechnung erstellen", invoiceTitle: "RECHNUNG", invoiceFrom: "Von", invoiceTo: "An", invoiceDate: "Datum", invoiceNumber: "Rechnungsnr.", invoiceItem: "Artikel", invoiceQty: "Anz.", invoiceUnitPrice: "Einzelpreis", invoiceAmount: "Betrag", invoiceSubtotal: "Zwischensumme", invoiceTotal: "Gesamtbetrag", invoiceNotes: "Anmerkungen", invoiceGenerated: "Rechnung erfolgreich erstellt.", invoiceError: "Rechnung konnte nicht erstellt werden.", shareInvoice: "Rechnung teilen", invoiceThankYou: "Vielen Dank f\u00FCr Ihren Einkauf!", orderDate: "Datum", orderDatePlaceholder: "Auftragsdatum", processingStatus: "Bearbeitungsstatus", processingStatusTodo: "Zu erledigen", processingStatusInProgress: "In Bearbeitung", processingStatusDone: "Erledigt", comment: "Kommentar", commentPlaceholder: "Interner Kommentar..." },
    markets: { title: "M\u00E4rkte", noMarkets: "Noch keine M\u00E4rkte", noMarketsSub: "F\u00FCge dein erstes Marktevent hinzu, um Verk\u00E4ufe zu verfolgen", newMarket: "Neuer Markt", eventDetails: "Veranstaltungsdetails", marketName: "Marktname", location: "Ort (optional)", costs: "Kosten", standFee: "Standgeb\u00FChr", travelCost: "Fahrtkosten", notes: "Notizen", additionalNotes: "Zus\u00E4tzliche Notizen (optional)", createMarket: "Markt erstellen", marketDetails: "Marktdetails", sales: "Verk\u00E4ufe", profit: "Gewinn", costBreakdown: "Kosten\u00FCbersicht", travel: "Fahrt", noSales: "Noch keine Verk\u00E4ufe. Verwende den + Button, um schnell Verk\u00E4ufe hinzuzuf\u00FCgen.", itemDescription: "Artikelbeschreibung", deleteSale: "Verkauf l\u00F6schen", removeSale: "Diesen Verkauf entfernen?", deleteMarket: "Markt l\u00F6schen", deleteMarketConfirm: "Dadurch werden auch alle zugeh\u00F6rigen Verk\u00E4ufe entfernt.", deleteCancel: "Abbrechen", deleteAction: "L\u00F6schen" },
    expenses: { title: "Ausgaben", noExpenses: "Noch keine Ausgaben", noExpensesSub: "Verfolge deine Gesch\u00E4ftsausgaben f\u00FCr genauen Gewinn", newExpense: "Neue Ausgabe", description: "Beschreibung", whatSpent: "Wof\u00FCr hast du ausgegeben?", amount: "Betrag", category: "Kategorie", addExpense: "Ausgabe hinzuf\u00FCgen", expenseDate: "Datum", expenseDatePlaceholder: "Ausgabedatum", deleteExpense: "Ausgabe l\u00F6schen", areYouSure: "Bist du sicher?", cancel: "Abbrechen", delete: "L\u00F6schen", total: "Gesamt", categories: { Materials: "Materialien", Shipping: "Versand", Subscriptions: "Abonnements", Tools: "Werkzeuge", Marketing: "Marketing", Packaging: "Verpackung", Other: "Sonstiges" } },
    settings: { title: "Einstellungen", companyProfile: "Firmenprofil", companyName: "Firmenname", address: "Adresse", email: "E-Mail", phone: "Telefon", taxNote: "Steuerhinweis (auf Rechnungen)", taxNotePlaceholder: "z.B. Gem. §19 UStG wird keine Umsatzsteuer berechnet.", smallBusinessNote: "Kleinunternehmer-Hinweis", defaultShippingCost: "Standardversandkosten", notSet: "Nicht gesetzt", dataBackup: "Daten & Sicherung", exportBackup: "Backup exportieren", restoreBackup: "Aus Backup wiederherstellen", factoryReset: "Werkseinstellungen", privacy: "Datenschutz", privacyText: "Vendora speichert deine Daten sicher in der Cloud, gesch\u00FCtzt durch dein Konto. Kein Tracking, keine Analysen. Du besitzt 100% deiner Daten.", exportComplete: "Export abgeschlossen", exportSuccess: "Deine Daten wurden erfolgreich exportiert.", exportFailed: "Export fehlgeschlagen", exportError: "Daten konnten nicht exportiert werden. Bitte versuche es erneut.", importComplete: "Import abgeschlossen", importSuccess: "Deine Daten wurden erfolgreich wiederhergestellt.", importFailed: "Import fehlgeschlagen", importError: "Die Backup-Datei konnte nicht gelesen werden. Bitte versuche es erneut.", resetTitle: "Werkseinstellungen", resetMessage: "Dadurch werden alle Daten dauerhaft gel\u00F6scht. Diese Aktion kann nicht r\u00FCckg\u00E4ngig gemacht werden.", resetCancel: "Abbrechen", resetAction: "Alles l\u00F6schen", resetComplete: "Zur\u00FCcksetzen abgeschlossen", resetSuccess: "Alle Daten wurden gel\u00F6scht.", language: "Sprache", appearance: "Darstellung", dark: "Dunkel", light: "Hell", system: "System" },
    tabs: { dashboard: "Dashboard", orders: "Auftr\u00E4ge", markets: "M\u00E4rkte", expenses: "Ausgaben", settings: "Einstellungen" },
    common: { loading: "Laden...", cancel: "Abbrechen", delete: "L\u00F6schen", confirm: "Best\u00E4tigen", save: "Speichern" },
    auth: { login: "Anmelden", register: "Registrieren", email: "E-Mail", password: "Passwort", confirmPassword: "Passwort best\u00E4tigen", loginSubtitle: "Melde dich bei deinem Konto an", registerSubtitle: "Erstelle dein Konto", noAccount: "Noch kein Konto?", hasAccount: "Bereits ein Konto?", loginError: "Ung\u00FCltige E-Mail oder Passwort", registerError: "Konto konnte nicht erstellt werden. E-Mail ist m\u00F6glicherweise bereits vergeben.", passwordMismatch: "Passw\u00F6rter stimmen nicht \u00FCberein", passwordTooShort: "Passwort muss mindestens 8 Zeichen lang sein", logout: "Abmelden", account: "Konto", forgotPassword: "Passwort vergessen?", resetTitle: "Passwort zur\u00FCcksetzen", resetEmailSubtitle: "Gib deine E-Mail-Adresse ein und wir senden dir einen Reset-Link.", sendResetLink: "Reset-Link senden", resetSuccess: "Passwort zur\u00FCckgesetzt", resetSuccessMessage: "Pr\u00FCfe dein E-Mail-Postfach f\u00FCr den Reset-Link.", resetError: "Reset-Link konnte nicht gesendet werden. Bitte versuche es erneut." },
    subscription: { trialDaysLeft: "Noch {days} Tage in deiner kostenlosen Testphase", expired: "Testphase beendet", expiredSub: "Abonniere Vendora, um neue Auftr\u00E4ge, M\u00E4rkte & Ausgaben zu erstellen.", upgrade: "Abonnieren", upgradeTitle: "Vendora abonnieren", upgradeDescription: "Unbegrenzter Zugang zu allen Funktionen f\u00FCr nur 2,99\u20AC/Monat.", upgradeButton: "Abonnieren f\u00FCr 2,99\u20AC/Monat", features: "Auftr\u00E4ge & Rechnungen erstellen, M\u00E4rkte verfolgen, Ausgaben verwalten", currentPlan: "Aktueller Plan", trial: "Kostenlose Testphase", active: "Aktives Abonnement", cancelled: "Gek\u00FCndigt", readOnly: "Diese Funktion erfordert ein aktives Abonnement." },
    months: ["Jan", "Feb", "M\u00E4r", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"],
  },
};

export type Translations = typeof translations.en;

export function getDeviceLanguage(): Language {
  if (typeof navigator !== "undefined") {
    return navigator.language?.startsWith("de") ? "de" : "en";
  }
  return "en";
}

export function getTranslations(lang: Language): Translations {
  return translations[lang];
}

export { translations };
