import type { MetadataRoute } from "next";

// Web App Manifest (Next.js metadata route → served at /manifest.webmanifest and
// auto-linked in <head>). Makes Vendora installable as a PWA for the offline
// market mode (Phase 3). Icons are generated by scripts/generate-pwa-icons.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Vendora – Marktverwaltung",
    short_name: "Vendora",
    description:
      "Marktmodus, Aufträge, Rechnungen und EÜR für Markthändler:innen – offline-fähig.",
    lang: "de",
    dir: "ltr",
    display: "standalone",
    orientation: "portrait",
    start_url: "/dashboard",
    scope: "/",
    theme_color: "#D4AF37",
    background_color: "#FAFAFA",
    categories: ["business", "finance", "productivity"],
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon-192-maskable.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icon-512-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
